#!/bin/bash
// Simple command to turn on and off power sockets on APC 7900 PDUs via SNMP
// Usage: pdu PDU_IP PDU_PORT ON|OFF|STATUS

ip=$1
port=$2

function status {
	status=$(snmpget -v2c -c private $ip 1.3.6.1.4.1.318.1.1.12.3.3.1.1.4.$port | cut -d: -f2)
        if [ "$status" -eq "2" ]; then
        	echo OFF
        elif [ "$status" -eq "1" ]; then
                echo ON
        else
                echo $status
        fi
}

case $3 in
        start|on ) 
		if [ $(status) == "OFF" ]; then
			snmpset -v2c -c private $ip 1.3.6.1.4.1.318.1.1.12.3.3.1.1.4.$port integer 1 > /dev/null && echo Turned port $port ON on $ip
		else
			echo "Port $port on $ip already on"
		fi
                ;;
        stop|off )
		if [ $(status) == "ON" ]; then
			snmpset -v2c -c private $ip 1.3.6.1.4.1.318.1.1.12.3.3.1.1.4.$port integer 2 > /dev/null  && echo Turned port $port OFF on $ip
		else
			echo "Port $port on $ip already off"
		fi
                ;;
        status ) status
                ;;
        * ) 	echo Toggle ports on APC PDUs
		echo Usage: $0 IP PORT STATE
		echo
                ;;
esac
