#!/bin/bash
minchecktime=15

function getdistance {
	distance=$(closesttohome.php)
}

getdistance
sleep 30
getdistance
echo distance=$distance > /tmp/distance.ini

#if distance is 0 or 1, assume we're home and check every minchecktime
if [ "$distance" -le 1 ]; then
	echo $0 | at now + $minchecktime min
#check frequently if we're close to home
elif [ "$distance" -lt 5 ]; then
	echo $0 | at now + $minchecktime min
#else check only as frequently as necessary
else
        #take estimated time away and check within 80% of that length
        checktime=$(((($distance*100)-($distance*20))/100))
        echo $0 | at now + $checktime min
fi
